# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias ssh="ssh -Y"
alias lxplus="ssh -Y lxplus.cern.ch"
alias lxplus5="ssh -Y lxplus5.cern.ch"
alias psi5="ssh -Y t3ui05.psi.ch"
alias psi="ssh -Y t3ui15.psi.ch"
alias bastion="ssh -Y bastion.desy.de"
alias atlnaf="~/scripts/naflogin.sh"
alias cmsnaf="~/scripts/cmsnaf.sh"
alias atlnaftoken="sh ~/scripts/naf_token.sh $USER"
alias cmsnaftoken="sh ~/scripts/cmsnaf_token.sh cmslange"
alias cmsnaf2="ssh -Y nafhh-cms05.desy.de"
alias atlnaf2="ssh -Y nafhh-atlas01.desy.de"
alias pixcr="ssh -Y pc4634.cern.ch"
alias libsvn="ssh -Y libuzhcm@lxplus.cern.ch"
alias myscp="rsync -avzP"
alias iniroot="cd /usr/root/current; source bin/thisroot.sh; cd -"
alias wakedge="wakeonlan f8:b1:56:bf:42:12"

# single window mode
singleWindowOn="defaults write com.apple.dock single-app -bool true; killall Dock"
singleWindowOff="defaults write com.apple.dock single-app -bool false; killall Dock"

export PYTHONPATH=$PYTHONPATH:$HOME/Library/Python/2.7/site-packages

KRB5_CONFIG=~/scripts/CERNkrb5.conf

export EDITOR="/usr/local/bin/mate -w"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git svn python pip dirhistory common-aliases brew osx web-search)

source $ZSH/oh-my-zsh.sh

function playmidi {

    SOUNDFONT='/usr/local/share/fluidsynth/generaluser.v.1.44.sf2'

    if [ -e "$SOUNDFONT" ]
    then 

        for i in "$@"
        do 
            if [ -e "$i" ]
            then
                (fluidsynth -i "$SOUNDFONT" "$i"  2>&1) >/dev/null
            else
                echo "[playmidi]: cannot find file at $i"   
                return 1
            fi  
        done 
    else
            echo "[playmidi]: SOUNDFONT file not found at $SOUNDFONT"
            return 1
    fi  
}

# Customize to your needs...
export PATH=$HOME/anaconda/bin:/usr/root/current/bin:/opt/local/bin:/opt/local/sbin:/opt/ldg/bin:/opt/ldg/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/texbin:$HOME/bin:$HOME/cms-git-tools:
